dist: trusty
sudo: required

language: go
directories:
    - $HOME/.glide/cache
go:
  - 1.7

addons:
  apt:
    packages:
    - python
    - libsnappy-dev
    - zlib1g-dev
    - libbz2-dev
    - libgflags-dev

before_install:
  - sudo apt-get remove gcc -y
  - pip install --user ccm
  - pip install --user cqlsh==5.0.3
  - sudo apt-get install gcc g++ -y

install:
  - go get -u github.com/Masterminds/glide
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - ccm create test -v 2.2.8 -n 1 -s
  - sudo ln -sf /home/travis/.local/bin/cqlsh /usr/local/bin/cqlsh
  - glide install && touch vendor/glide.updated
  - pushd vendor/github.com/cockroachdb/c-rocksdb/internal
  - travis_wait 20 make shared_lib
  - popd
  - export CGO_CFLAGS="$CGO_FLAGS -I`pwd`/vendor/github.com/cockroachdb/c-rocksdb/internal/include"
  - export CGO_LDFLAGS="$CGO_LDFLAGS -L`pwd`/vendor/github.com/cockroachdb/c-rocksdb/internal -lrocksdb"
  - export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:`pwd`/vendor/github.com/cockroachdb/c-rocksdb/internal"

script:
  - EMBEDROCKSDB=0 make cover_ci
